### ISSUE TITLE
4305 desktop ram fix

### ISSUE THREAD

**Issue by smower476** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#16]
Hello
Is there a mod for du994305 with desktop ram fix for v4 CPUs?
I can also attach a BIOS backup if you need

**Comment by jwagnervaz** [comment]
> Hello
> Is there a mod for du994305 with desktop ram fix for v4 CPUs?
> I can also attach a BIOS backup if you need

Hi, what you mean about ram fix for v4 ?

**Comment by smower476** [comment]
> V4 is not supposed to work with Desktop ram, but some people said it works only with 1 cpu.

Yes, this is a problem. With 1 cpu everything works fine, but with both i get post code 79. Someone said that this bug exists only on this motherboard and can be fixed with modded BIOS, so I'm looking for it.

**Comment by jwagnervaz** [comment]
@smower476 

Did test with this Desktop RAM
to reproduce
ASGARD
W2 DDR4 PC 8G or 16GB
VMA45UG-MEC1U2AW2 8GB
VMA45UG-MEC16U2AW2 16GB

get
ERROR 79

with 1 and 2 CPU 2680 V4.  (ERROR 79)

The problem is  V4 dont support desktop RAM at IMC level.
Maybe fixable via a BIOS patch ( too complicated to find)

These RAM dont work (error 79) even with E5 2670 V3. Tested in a QIYLDA X99 D4 (SINGLE CPU) and a AIGO X99L D4

Safe to say that some chinese RAM has FAKE SPI info. (IMC dont recognize no matter if its V3 or V4 CPU)

The case of this ASGARD VMA45UG-MEC16U2AW2  AND VMA45UG-MEC1U2AW2 8GB

With these said, what DUAL motheboard works with desktop ram with a  V4 ? Where did you see this info ?

**Comment by jwagnervaz** [comment]
> > V4 is not supposed to work with Desktop ram, but some people said it works only with 1 cpu.
> 
> Yes, this is a problem. With 1 cpu everything works fine, but with both i get post code 79. Someone said that this bug exists only on this motherboard and can be fixed with modded BIOS, so I'm looking for it.

Could you send RAM info after boot with 1 CPU V4 if this work for you?

You can use AIDA64 or  CPU-Z at SPD table.

thanks.

**Comment by smower476** [comment]
> Could you send RAM info after boot with 1 CPU V4 if this work for you?
![image](https://github.com/user-attachments/assets/16bce4e6-40a3-4872-b3b3-eeec647b9a29)
![image](https://github.com/user-attachments/assets/c57a601b-8aeb-462a-95e3-a347022ff386)

[Report.txt](https://github.com/user-attachments/files/17089508/Report.txt)

**Comment by smower476** [comment]
> Where did you see this info ?

This post https://forums.overclockers.ru/viewtopic.php?p=18146002#p18146002 (I can translate into English if necessary)

Theres also a BIOS that can theoretically work with desktop RAM, but I didn't risk flashing it since I don't have a programmer to restore the system

**Comment by jwagnervaz** [comment]
seams like https://www.patreon.com/BIOSiEngineer/shop/huananzhi-x99-f8-cx99de45-bios-5736?source=storefront

find out a way to make FAKE spi chinese UDIMM modules boot into a x99 system, im afraid i can reverse eng his bios and discovery what makes it boot, but im not about to spend money to something im not paid for....
it so sad that open source dont give us nothing.

a LOT of people are using my work for free(wont give numbers- life its not about it)  not iven a single donate i had received, so iven if i dont sell my work, i understant why  this guy IEngineers does....

so this way i afraid cant help you with it.

**Comment by jwagnervaz** [comment]
Closed
