### ISSUE TITLE
SAS card not being recognized

### ISSUE THREAD

**Issue by jave808** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#17]
An issue of sorts, but not with the ROM/BIOS - or it could be.

I have a v1.3 board. I can get it to POST with a video card in either PCIex16 slot. BUT when I have the video card in the 1st upper most slot AND my SAS (PCIex8) controller card in the 2nd PCIe slot, the system goes into the BIOS splash screen where it really should POST with the menu of the SAS controller card that is built-in.

Are there any settings that anyone knows about which will enable the SAS card to be recognized?

**Comment by jwagnervaz** [comment]
> An issue of sorts, but not with the ROM/BIOS - or it could be.
> 
> I have a v1.3 board. I can get it to POST with a video card in either PCIex16 slot. BUT when I have the video card in the 1st upper most slot AND my SAS (PCIex8) controller card in the 2nd PCIe slot, the system goes into the BIOS splash screen where it really should POST with the menu of the SAS controller card that is built-in.
> 
> Are there any settings that anyone knows about which will enable the SAS card to be recognized?

Its not a BIOS/ROM ussue, this is how a SAS card works since ever https://forum.level1techs.com/t/no-boot-no-display-with-sas-cards-installed/145790



Your SAS card, have module that folows some stardard, it coud be CSM only or could be UEFI, come have firmware updates to improve compat.  but as we can see. 

https://yannickdekoeijer.blogspot.com/2012/04/modding-dell-perc-6-sas-raidcontroller.html

some people have mask pins. to use in some system, 

Modding a Dell Perc 6 / Dell H310 / Dell H710 (other LSI 1078 or 9223-8i based) SAS Raidcontroller

Update:
This raidcontroller has been moved to another system with the same mod, and it works perfectly.
ASRock P67 Extreme 4
Intel I3 3220T
2x2GB DDR3
8x2TB attached to the perc 6


im way to be a sas programmer, i know a little about bios, but about SAS amous none, but i find this infos in secods, maybe you searching on worng spots.

i read that 

https://forums.servethehome.com/index.php?threads/pcie-sas-card-that-works-on-uefi.43790/

some modules have firmware update also. 

i wish you lucky on this jurney, but is clear that the problem its other thing than motheboard bios....

**Comment by jave808** [comment]
Thank you!! Your info gives me something to go off. I will investigate further. :-)
